# Generated by Django 3.2.7 on 2021-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candi_Personal',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=500)),
                ('Cemail', models.CharField(max_length=500)),
                ('Cphone', models.CharField(max_length=20, unique=True)),
                ('Cdesignation', models.CharField(max_length=500, null=True)),
                ('Cskills', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Resumes')),
            ],
        ),
    ]
