# Generated by Django 3.2.7 on 2021-10-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_of_cand', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_of_cand', models.CharField(max_length=240)),
            ],
        ),
        migrations.RemoveField(
            model_name='candi_personal',
            name='Cdesignation',
        ),
        migrations.RemoveField(
            model_name='candi_personal',
            name='Cskills',
        ),
        migrations.AlterField(
            model_name='candi_personal',
            name='Cemail',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='candi_personal',
            name='Cname',
            field=models.CharField(max_length=240),
        ),
        migrations.CreateModel(
            name='Cand_personal_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.candi_personal')),
                ('skillid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.skills')),
            ],
        ),
    ]
