# Generated by Django 3.2.7 on 2021-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20211011_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_of_cand',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_of_cand',
            field=models.TextField(),
        ),
    ]
