# Generated by Django 3.2.7 on 2021-10-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_auto_20211011_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candi_personal',
            name='Cemail',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candi_personal',
            name='Cname',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candi_personal',
            name='Cphone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_of_cand',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_of_cand',
            field=models.TextField(null=True),
        ),
    ]
