# Generated by Django 3.2.7 on 2021-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0004_auto_20211011_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candi_personal',
            name='Cphone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
